### ISSUE TITLE
Support SQLcipher

### ISSUE THREAD

**Issue by talmeme** [moshegottlieb/SwiftSQLite#2]
As subject. See [ sqlcipher branch of my fork](https://github.com/talmeme/SwiftSQLite/tree/sqlcipher).

**Comment by moshegottlieb** [comment]
Interesting!  
I will look for a way to integrate it.  
Since it's compatible with standard SQLite3 format, it's probably ok to include the SQL Cipher code, and omit the original SQLite dependency.  
It would require me to monitor for security notifications on SQL Cipher though.  
Will ponder on it until I have a bit more time.  
Thanks!

**Comment by moshegottlieb** [comment]
Added support in v1.1.0
